version: '3.4'

services:
  wallet.services.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  wallet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

