version: '3.4'

services:

  rabbitmq:
    image: rabbitmq
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 30s
        timeout: 10s
        retries: 5

  wallet.sql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    ports: 
    - "1433:1433"

  wallet.services.identity:
    image: ${DOCKER_REGISTRY-}walletservicesidentity
    build:
      context: .
      dockerfile: Wallet.Services.Identity/Dockerfile
    restart: on-failure
    ports: 
      - "5001:80"
    depends_on:
      - rabbitmq
      - wallet.sql  

  wallet.services.accounts:
    image: ${DOCKER_REGISTRY-}walletservicesaccounts
    build:
      context: .
      dockerfile: Wallet.Services.Accounts/Dockerfile
    restart: on-failure
    ports: 
      - "5002:80"
    depends_on:
      - rabbitmq
      - wallet.sql  
      - wallet.services.currency
      - wallet.services.identity
      
  wallet.services.currency:
    image: ${DOCKER_REGISTRY-}walletservicescurrency
    build:
      context: .
      dockerfile: Wallet.Services.Currency/Dockerfile
    restart: on-failure
    ports: 
      - "5003:80"
    depends_on:
      - rabbitmq
      - wallet.sql  
      - wallet.services.identity

  wallet.services.transactions:
    image: ${DOCKER_REGISTRY-}walletservicestransactions
    build:
      context: .
      dockerfile: Wallet.Services.Transactions/Dockerfile
    restart: on-failure
    ports: 
      - "5004:80"
    depends_on:
      - rabbitmq
      - wallet.sql  
      - wallet.services.currency
      - wallet.services.identity

  wallet.api:
    image: ${DOCKER_REGISTRY-}walletapi
    build:
      context: .
      dockerfile: Wallet.Api/Dockerfile
    restart: on-failure
    ports: 
      - "5000:80"
    depends_on:
      - rabbitmq
      - wallet.sql  
      - wallet.services.identity
      - wallet.services.currency
      - wallet.services.accounts
      - wallet.services.transactions

  wallet.webspa:
    image: ${DOCKER_REGISTRY-}walletwebspa
    build:
      context: .
      dockerfile: Wallet.WebSPA/Dockerfile
    ports: 
      - "5010:80"
    depends_on:
      - wallet.api






