version: '3.4'

services:
  wallet.services.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  wallet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  wallet.webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  wallet.services.accounts:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  wallet.services.transactions:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  wallet.services.currency:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

